[package]
name = "graphql_intro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.28", features = ["compat"] }
futures-macro = "0.3.28"
juniper = { version = "0.15.11", features = ["graphql-parser", "graphql-parser-integration", "schema-language", "url", "anyhow"] }
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["macros", "full"] }
tokio-postgres = { version = "0.7.8", features = ["with-uuid-0_8"] }
uuid = { version = "1.3.1", features = ["v4"] }
warp = "0.3.4"
