[workspace]
members = [
  "async",
  "async_router",
  "crypto",
  "fs",
  "graphviz",
  "graphql_intro",
  "hello_world",
  "helloworld-tonic",
  "ipfs",
  "peano",
  "petgraph",
  "practice",
  "rbe",
  "tree",
  "voting-tonic",
]

resolver = "2"
